---
title: "An치lisis Descriptivo California"
output: html_document
---

## Carga inicial

* Carga del dataset original
```{r}
#url <- 'https://github.com/hrodriguezgi-un/elemprobest/raw/main/sources/daily_weather_2020.csv'
url <- '/Users/hrodriguez/Downloads/daily_weather_2020.csv'
all_countries <- read.csv(url)
```

* Creaci칩n de dataframe para New York
```{r}
new_york <- subset(all_countries, Country.Region == 'US' & Province.State == 'New York')
```

## An치lisis de California
### Pruebas de normalidad
* qqPlot e histograma para los datos de Temperatura
```{r}
par(mfrow=c(1, 2))
require(car)

qqPlot(california$temperatureHigh, pch = 19,
       main = 'QQplot Temp. California',
       ylab = 'Cuantiles muestrales',
       xlab = 'Cuantiles te칩ricos')

hist(california$temperatureHigh, freq = T,
     main='Hist. Temp. California',
     ylab = 'Frecuencia',
     xlab = 'Temperatura')
```
### Tablas de frecuencia
```{r}
table(california$icon)
```


[regresar](https://hrodriguezgi-un.github.io/elemprobest/descripcion_bbdd)
[siguiente](https://hrodriguezgi-un.github.io/elemprobest/descriptivo_newyork)