---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

## Carga inicial

* Carga del dataset original
```{r}
url <- 'https://github.com/hrodriguezgi-un/elemprobest/raw/main/sources/daily_weather_2020.csv'
all_countries <- read.csv(url)
```

* Creaci贸n de dataframe para San Francisco
```{r}
california <- subset(all_countries, Country.Region == 'US' & Province.State == 'California')
```

* Creaci贸n de dataframe para New York
```{r}
new_york <- subset(all_countries, Country.Region == 'US' & Province.State == 'New York')
```

## Pruebas de normalidad para los datos de San Francisco
* qqPlot e histograma para los datos de Temperatura
```{r}
par(mfrow=c(1, 2))
require(car)

qqPlot(california$temperatureHigh, pch = 19,
       main = 'QQplot temperatura California',
       ylab = 'Cuantiles muestrales',
       xlab = 'Cuantiles te贸ricos')

hist(california$temperatureHigh, freq = T,
     main='Histograma temperatura California',
     ylab = 'Frecuencia',
     xlab = 'Temperatura')
```

## Pruebas de normalidad para los datos de New York
* qqPlot e histograma para los datos de Temperatura
```{r}
par(mfrow=c(1, 2))
require(car)

qqPlot(new_york$temperatureHigh, pch = 19,
       main = 'QQplot temperatura New York',
       ylab = 'Cuantiles muestrales',
       xlab = 'Cuantiles te贸ricos')

hist(new_york$temperatureHigh, freq = T,
     main='Histograma temperatura New York',
     ylab = 'Frecuencia',
     xlab = 'Temperatura')
```