---
title: "Intervalos de Confianza y Pruebas de Hipótesis"
author: "Harvey Rodriguez Gil"
date: "Mayo 7, 2021"
output: ioslides_presentation
---

## Carga inicial

* Carga del dataset original
```{r}
#url <- 'https://github.com/hrodriguezgi-un/elemprobest/raw/main/sources/daily_weather_2020.csv'
url <- '/Users/hrodriguez/Downloads/daily_weather_2020.csv'
all_countries <- read.csv(url)
```

* Creación de dataframe para New York
```{r}
new_york <- subset(all_countries, Country.Region == 'US' & Province.State == 'New York')
```

## New York
### Pruebas de normalidad
* qqPlot e histograma para los datos de Temperatura
```{r}
par(mfrow=c(1, 2))
require(car)

qqPlot(new_york$temperatureHigh, pch = 19,
       main = 'QQplot Temp. New York',
       ylab = 'Cuantiles muestrales',
       xlab = 'Cuantiles teóricos')

hist(new_york$temperatureHigh, freq = T,
     main='Hist. Temp. New York',
     ylab = 'Frecuencia',
     xlab = 'Temperatura')
```

### Tablas de frecuencia
* Ícono para representación del clima:
```{r}
table(new_york$icon)
```

[regresar](https://hrodriguezgi-un.github.io/elemprobest/descriptivo_california.html)
[siguiente]()